# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=128, verbose_name='Internal Name')),
                ('app_display_name', models.CharField(default='', max_length=128, verbose_name='Display Name')),
                ('app_url', models.CharField(default='', max_length=1024, verbose_name='URL')),
                ('app_short_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Short Description')),
                ('app_long_description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Long Description')),
                ('app_icon_cls', models.CharField(blank=True, help_text='CSS class used for small icons', max_length=128, null=True, verbose_name='Icon CSS Class')),
                ('app_icon_src', models.CharField(blank=True, help_text='path to the applications icon.', max_length=1024, null=True, verbose_name='Icon Source')),
                ('app_video_src', models.CharField(blank=True, help_text='Url to video. eg. https://www.youtube.com/embed/XGSy3_Czz8k', max_length=2048, null=True, verbose_name='Video Source')),
                ('app_order', models.IntegerField(blank=True, help_text='Order in menu.', null=True, verbose_name='Order')),
                ('app_disabled', models.BooleanField(default=False, help_text='mark True to disable this application in the menu.', verbose_name='Disabled')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttr_title', models.CharField(default='', max_length=1024, verbose_name='Title')),
                ('ttr_src', models.CharField(blank=True, help_text='Url to video. eg. https://www.youtube.com/embed/XGSy3_Czz8k', max_length=2048, null=True, verbose_name='Video Source')),
                ('ttr_description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.Application', verbose_name='Application')),
            ],
        ),
    ]
