# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_auto_20160701_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
