# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interfaces', '0002_auto_20160705_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_display_name',
            field=models.CharField(default='', max_length=128, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_icon_cls',
            field=models.CharField(blank=True, help_text='CSS class used for small icons', max_length=128, null=True,
                                   verbose_name='Icon CSS Class'),
        ),
        migrations.AddField(
            model_name='application',
            name='app_icon_src',
            field=models.CharField(blank=True, help_text='path to the applications icon.', max_length=1024, null=True,
                                   verbose_name='Icon Source'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_long_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(default='', max_length=128, verbose_name='Internal Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_short_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_url',
            field=models.URLField(default='', max_length=1024, verbose_name='URL'),
        ),
    ]
