# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interfaces', '0003_auto_20160920_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_order',
            field=models.IntegerField(blank=True, help_text='Order in menu.', null=True, verbose_name='Order'),
        ),
    ]
