# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interfaces', '0004_application_app_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_disabled',
            field=models.BooleanField(default=False, help_text='mark True to disable this application in the menu.',
                                      verbose_name='Disabled'),
        ),
    ]
