# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interfaces', '0005_application_app_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_long_description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_short_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_url',
            field=models.CharField(default='', max_length=1024, verbose_name='URL'),
        ),
    ]
