# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_auto_20160921_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_video_src',
            field=models.CharField(blank=True, help_text='Url to video. eg. https://www.youtube.com/embed/XGSy3_Czz8k', max_length=2048, null=True, verbose_name='Video Source'),
        ),
    ]
