# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0007_application_app_video_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttr_title', models.CharField(default='', max_length=1024, verbose_name='Title')),
                ('ttr_src', models.CharField(blank=True, help_text='Url to video. eg. https://www.youtube.com/embed/XGSy3_Czz8k', max_length=2048, null=True, verbose_name='Video Source')),
                ('ttr_description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.Application', verbose_name='Application')),
            ],
        ),
    ]
