# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-14 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0008_tutorials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
    ]
