# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rls_name', models.CharField(max_length=60, verbose_name='Name')),
                ('rls_version', models.CharField(blank=True, max_length=60, null=True, verbose_name='Version')),
                ('rls_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('rls_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rls_doc_url', models.URLField(blank=True, null=True, verbose_name='Doc Url')),
                ('rls_display_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Display Name')),
            ],
        ),
    ]
