# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tiles',
        ),
    ]
