# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0006_auto_20160308_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='coadd.Release', verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_decll',
            field=models.FloatField(blank=True, null=True, verbose_name='Decll'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_declr',
            field=models.FloatField(blank=True, null=True, verbose_name='Declr'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_decul',
            field=models.FloatField(blank=True, null=True, verbose_name='Decul'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_decur',
            field=models.FloatField(blank=True, null=True, verbose_name='Decur'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_rall',
            field=models.FloatField(blank=True, null=True, verbose_name='RAll'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_ralr',
            field=models.FloatField(blank=True, null=True, verbose_name='RAlr'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_raul',
            field=models.FloatField(blank=True, null=True, verbose_name='RAul'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_raur',
            field=models.FloatField(blank=True, null=True, verbose_name='RAur'),
        ),
    ]
