# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0008_filters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Filter',
        ),
    ]
