# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 16:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0010_auto_20160420_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv_project', models.CharField(blank=True, max_length=20, null=True, verbose_name='Project')),
                ('srv_display_name', models.CharField(max_length=80, verbose_name='Display Name')),
                ('srv_url', models.URLField(verbose_name='URL')),
                ('srv_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Filter',
                                                 verbose_name='Filter')),
                ('srv_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys',
                                                  to='coadd.Release', verbose_name='Release')),
            ],
        ),
    ]
