# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0012_auto_20160428_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='rls_default',
            field=models.BooleanField(default=False,
                                      help_text='Mark this release as Default so that the interfaces can select this release previously.',
                                      verbose_name='Default'),
        ),
    ]
