# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.PositiveIntegerField()),
                ('exp_username', models.CharField(max_length=128)),
                ('exp_date', models.DateTimeField()),
                ('exp_product_id', models.PositiveIntegerField()),
                ('exp_external_process', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epr_id', models.PositiveIntegerField()),
                ('epr_name', models.CharField(max_length=128)),
                ('epr_username', models.CharField(max_length=128)),
                ('epr_start_date', models.DateTimeField()),
                ('epr_end_date', models.DateTimeField()),
                ('epr_readme', models.CharField(max_length=128)),
                ('epr_comment', models.CharField(max_length=128)),
                ('epr_original_id', models.PositiveIntegerField()),
                ('epr_site', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ste_id', models.PositiveIntegerField()),
                ('ste_name', models.CharField(max_length=128)),
                ('ste_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upl_id', models.PositiveIntegerField()),
            ],
        ),
    ]
