# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 18:43
from __future__ import unicode_literals

import current_user
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product_register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coadd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ath_ticket', models.CharField(default=product_register.models.Authorization.ticket, max_length=6, verbose_name='Ticket')),
                ('ath_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ath_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_username', models.CharField(blank=True, max_length=128, null=True, verbose_name='User Name')),
                ('exp_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epr_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('epr_username', models.CharField(help_text='original process username on your instances of origin.', max_length=128, verbose_name='Original Owner')),
                ('epr_original_id', models.CharField(help_text='original process id on your instances of origin.', max_length=128, null=True, verbose_name='Original Id')),
                ('epr_start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start Date')),
                ('epr_end_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='End Date')),
                ('epr_readme', models.CharField(blank=True, max_length=128, null=True, verbose_name='Readme')),
                ('epr_comment', models.CharField(blank=True, help_text='Process submission comment.', max_length=128, null=True, verbose_name='Comment')),
                ('epr_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_register.ExternalProcess')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Release')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sti_name', models.CharField(max_length=128, verbose_name='Site')),
                ('sti_url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('sti_user', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
        migrations.AddField(
            model_name='externalprocess',
            name='epr_site',
            field=models.ForeignKey(blank=True, default=None, help_text='origin of the process. instance from which it was imported.', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_register.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='externalprocess',
            name='releases',
            field=models.ManyToManyField(default=None, through='product_register.ProcessRelease', to='coadd.Release', verbose_name='Releases'),
        ),
        migrations.AddField(
            model_name='export',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_register.ExternalProcess'),
        ),
    ]
