# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_comment',
            field=models.CharField(help_text='Process submission comment.', max_length=128, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_name',
            field=models.CharField(max_length=128, verbose_name='Internal Name'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_original_id',
            field=models.PositiveIntegerField(help_text='original process id on your instances of origin.',
                                              verbose_name='Original Id'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_readme',
            field=models.CharField(max_length=128, verbose_name='Readme'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_site',
            field=models.CharField(help_text='origin of the process. instance from which it was imported.',
                                   max_length=128, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_username',
            field=models.CharField(max_length=128, verbose_name='User Name'),
        ),
    ]
