# Generated by Django 2.1.5 on 2019-02-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='sti_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
    ]
