# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0004_auto_20160722_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='sti',
            new_name='sti_user',
        ),
    ]
