# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_register', '0005_auto_20160725_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_comment',
            field=models.CharField(blank=True, help_text='Process submission comment.', max_length=128, null=True,
                                   verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Internal Name'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_original_id',
            field=models.PositiveIntegerField(help_text='original process id on your instances of origin.', null=True,
                                              verbose_name='Original Id'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_readme',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Readme'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
