# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product_register.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_register', '0006_auto_20160726_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ath_ticket', models.CharField(default=product_register.models.Authorization.ticket, max_length=6, verbose_name='Ticket')),
                ('ath_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ath_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
