# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_register', '0007_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprocess',
            name='epr_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
