# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0008_externalprocess_epr_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_username',
            field=models.CharField(help_text='original process username on your instances of origin.', max_length=128, verbose_name='Original Owner'),
        ),
    ]
