# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0013_auto_20161215_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_register.ExternalProcess'),
        ),
    ]
