# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0014_export_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprocess',
            name='epr_site',
            field=models.ForeignKey(blank=True, default=None, help_text='origin of the process. instance from which it was imported.', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_register.Site', verbose_name='Site'),
        ),
    ]
