version: '2'
services:

  backend:
    build: ./api
    command: ./entrypoint.sh
    environment:
      - NCSA=true
      - CELERY_BROKER=amqp://dri:adminadmin@rabbit:5672
    depends_on:
      - rabbit

  rabbit:
      image: rabbitmq:3-management
      hostname: rabbit_dri
      environment:
          - RABBITMQ_DEFAULT_USER=dri
          - RABBITMQ_DEFAULT_PASS=adminadmin
      ports:
          - "5672:5672"
          - "15672:15672"

  iipserver:
    image: linea/iipserver:latest
    environment:
      - LOGFILE=/log/iipsrv.log
      - VERBOSITY=10
      - FILESYSTEM_PREFIX=/images/
      - MAX_IMAGE_CACHE_SIZE=10
      - MAX_CVT=3000
      - JPEG_QUALITY=90
    command: ./start_fcgi.sh
    volumes:
      - ./log:/log
      - ./archive:/images

  nginx:
    build: ./frontend
    ports:
      - 80:8080
    depends_on:
      - backend
