# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=128, verbose_name='Internal Name')),
                ('prd_display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('prd_flag_removed', models.BooleanField(default=False, verbose_name='Mark a product as removed')),
                ('prd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ProductClass')),
            ],
        ),
    ]
