# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('fli_base_path', models.CharField(max_length=256, verbose_name='Base path')),
                ('fli_name', models.CharField(max_length=128, verbose_name='Filename with extension')),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('tbl_schema', models.CharField(max_length=128, verbose_name='Schema name')),
                ('tbl_name', models.CharField(max_length=128, verbose_name='Tablename without schema')),
            ],
            bases=('product.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='prd_description',
            field=models.CharField(default='test', max_length=1024, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prd_version',
            field=models.CharField(default='1', max_length=128, verbose_name='Version'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Table')),
                ('ctl_num_columns', models.PositiveIntegerField(verbose_name='Num of columns')),
                ('ctl_num_tiles', models.PositiveIntegerField(verbose_name='Num of tiles')),
                ('ctl_num_objects', models.PositiveIntegerField(verbose_name='Num of objects')),
            ],
            bases=('product.table',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Table')),
                ('mpa_nside', models.PositiveSmallIntegerField(verbose_name='Nside')),
                ('mpa_filter', models.CharField(max_length=1, verbose_name='Filter')),
                ('mpa_ordering', models.CharField(max_length=8, verbose_name='Ordering')),
            ],
            bases=('product.table',),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Table')),
                ('msk_filter', models.CharField(max_length=1, verbose_name='Filter')),
            ],
            bases=('product.table',),
        ),
    ]
