# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160405_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ProductClass', verbose_name='Product class'),
        ),
    ]
