# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20171206_1750'),
        ('coadd', '0028_auto_20170807_1843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128, verbose_name='Name')),
                ('start_date_time', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Creation Date')),
                ('end_date_time', models.DateTimeField(blank=True, help_text='Last Edition Date', null=True, verbose_name='Last Edition Date')),
                ('sql_sentence', models.CharField(max_length=2048, verbose_name='Sql_sentence')),
                ('timeout', models.IntegerField(default=5, null=True, verbose_name='Query execution timeout in seconds')),
                ('job_status', models.CharField(choices=[('st', 'Starting'), ('rn', 'Running'), ('ok', 'Done'), ('er', 'Error')], default='st', max_length=25, verbose_name='Status')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Creation Date')),
                ('last_edition_date', models.DateTimeField(auto_now=True, help_text='Last Edition Date', null=True, verbose_name='Last Edition Date')),
                ('sql_sentence', models.CharField(max_length=2048, verbose_name='Sql Sentence')),
                ('is_sample', models.BooleanField(default=False, verbose_name='Is a sample query')),
                ('is_public', models.BooleanField(default=False, help_text='Is Public default True', verbose_name='Is Public')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Release')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=128, verbose_name='Display name')),
                ('schema', models.CharField(max_length=128, null=True, verbose_name='Schema')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product', verbose_name='Product')),
            ],
        ),
    ]
