# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0002_auto_20170302_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Is Public default True', verbose_name='Is Public'),
        ),
    ]
