# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0002_auto_20171207_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coadd.Release'),
        ),
    ]
