# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-27 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0003_userquery_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='owner',
        ),
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
