# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0004_job_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tbl_num_objects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of rows'),
        ),
    ]
