# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-27 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userquery', '0004_auto_20171027_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('query', models.CharField(blank=True, max_length=1024, verbose_name='Query')),
                ('creationdate', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Date')),
                ('tablename', models.CharField(blank=True, max_length=128, verbose_name='Table Name')),
                ('is_public', models.BooleanField(default=False, help_text='Is Public default True', verbose_name='Is Public')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
