# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-14 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0005_table_tbl_num_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
