# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0005_userquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuery',
            new_name='Query',
        ),
    ]
