# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0006_auto_20171030_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='tablename',
            new_name='table_name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='creationdate',
        ),
        migrations.AddField(
            model_name='query',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='query',
            name='is_validate',
            field=models.BooleanField(default=False, verbose_name='Is Query Validated'),
        ),
        migrations.AddField(
            model_name='query',
            name='last_edition_date',
            field=models.DateTimeField(auto_now=True, help_text='Last Edition Date', null=True, verbose_name='Last Edition Date'),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Query'),
        ),
    ]
