# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0006_auto_20171214_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='display_name',
            field=models.CharField(max_length=128, verbose_name='Display name'),
        ),
    ]
