# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0007_auto_20171030_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(max_length=2048, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='query',
            name='table_name',
            field=models.CharField(max_length=128, verbose_name='Table Name'),
        ),
    ]
