# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0007_auto_20171214_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.TextField(default=0, verbose_name='Job Cerely ID'),
            preserve_default=False,
        ),
    ]
