# Generated by Django 2.1.5 on 2020-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0008_job_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Error'),
        ),
    ]
