# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-08 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userquery', '0008_auto_20171106_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Creation Date')),
                ('end_date_time', models.DateTimeField(blank=True, help_text='Last Edition Date', null=True, verbose_name='Last Edition Date')),
                ('sql_sentence', models.CharField(max_length=2048, verbose_name='Sql_sentence')),
                ('timeout', models.IntegerField(null=True, verbose_name='Query execution timeout in seconds')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
