# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('st', 'Starting'), ('vl', 'Validating query'), ('rn', 'Running'), ('ok', 'Done'), ('er', 'Error')], default='st', max_length=25, verbose_name='Status'),
        ),
    ]
