# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0010_job_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query',
        ),
        migrations.AddField(
            model_name='query',
            name='sql_sentence',
            field=models.CharField(default='', max_length=2048, verbose_name='Sql Sentence'),
            preserve_default=False,
        ),
    ]
