# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0011_auto_20171108_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='table_name',
        ),
        migrations.AddField(
            model_name='job',
            name='table_name',
            field=models.CharField(default='table_name', max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='timeout',
            field=models.IntegerField(default=5, null=True, verbose_name='Query execution timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(default='description', max_length=256, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
