# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-09 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0012_auto_20171109_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('st', 'Starting'), ('rn', 'Running'), ('ok', 'Done'), ('er', 'Error')], default='st', max_length=25, verbose_name='Status'),
        ),
    ]
