# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-09 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0028_auto_20170807_1843'),
        ('userquery', '0014_job_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='release',
        ),
        migrations.AddField(
            model_name='query',
            name='release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='coadd.Release', verbose_name='Release'),
            preserve_default=False,
        ),
    ]
