# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0015_auto_20171109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Release'),
        ),
    ]
