# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0017_auto_20171114_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='is_validate',
        ),
        migrations.AddField(
            model_name='query',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='Is a sample query'),
        ),
    ]
