# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0018_auto_20171116_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='table_name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
