# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_cutoutjob_cjb_image_formats'),
        ('userquery', '0022_auto_20171129_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='product_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.Product', verbose_name='Product'),
        ),
    ]
