# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-30 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0023_table_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='product_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product', verbose_name='Product'),
        ),
    ]
