# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-30 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0024_auto_20171130_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='product_id',
            new_name='product',
        ),
    ]
