# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0025_auto_20171130_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='table',
            name='display_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Display name'),
        ),
    ]
