# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-07 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0026_auto_20171206_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product', verbose_name='Product'),
        ),
    ]
