# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0028_auto_20170807_1843'),
        ('userquery', '0027_auto_20171207_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coadd.Release'),
            preserve_default=False,
        ),
    ]
