# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct_name', models.CharField(max_length=128, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcl_name', models.CharField(help_text='Internal name, unique', max_length=128, unique=True, verbose_name='Internal Name')),
                ('pcl_display_name', models.CharField(help_text='User-friendly display name', max_length=128, verbose_name='Display Name')),
                ('pcl_is_system', models.BooleanField(default=False, help_text='Is a system class type', verbose_name='System')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClassContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcc_name', models.CharField(help_text='Name of the content.', max_length=30, verbose_name='Name')),
                ('pcc_display_name', models.CharField(blank=True, help_text='Display Name of the content.', max_length=128, null=True, verbose_name='Display Name')),
                ('pcc_ucd', models.CharField(blank=True, help_text='The standard unified content descriptor.', max_length=128, null=True, verbose_name='UCD')),
                ('pcc_unit', models.CharField(blank=True, help_text='Content Unit e.g. name=ra unit=deg.', max_length=128, null=True, verbose_name='Unit')),
                ('pcc_reference', models.CharField(blank=True, help_text='Column Reference e.g. name=ra unit=dec reference=J2000.', max_length=128, null=True, verbose_name='Reference')),
                ('pcc_mandatory', models.BooleanField(default=False, help_text='Mark as true to indicate that this content is mandatory.', verbose_name='Mandatory')),
                ('pcc_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ContentCategory', verbose_name='Content Category')),
                ('pcc_class', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ProductClass', verbose_name='Product Class')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgr_name', models.CharField(help_text='Internal name, unique', max_length=128, unique=True, verbose_name='Internal Name')),
                ('pgr_display_name', models.CharField(help_text='User-friendly display name', max_length=128, verbose_name='Display Name')),
                ('is_catalog', models.BooleanField(default=False, help_text='Mark the group as catalog.', verbose_name='Is Catalog')),
            ],
        ),
        migrations.AddField(
            model_name='productclass',
            name='pcl_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ProductGroup', verbose_name='Group'),
        ),
    ]
