# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcl_name', models.CharField(max_length=128, verbose_name='Internal Name')),
                ('pcl_display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('pcl_is_system', models.BooleanField(default=False, verbose_name='System class type')),
            ],
        ),
    ]
