# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='pcl_display_name',
            field=models.CharField(max_length=128, verbose_name='User-friendly display name'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='pcl_is_system',
            field=models.BooleanField(default=False, verbose_name='Is a system class type'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='pcl_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Internal name, unique'),
        ),
    ]
