# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_classifier', '0002_auto_20160408_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgr_name', models.CharField(max_length=128, unique=True, verbose_name='Internal name, unique')),
                ('pgr_display_name', models.CharField(max_length=128, verbose_name='User-friendly display name')),
            ],
        ),
    ]
