# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_classifier', '0004_productclass_pcl_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='is_catalog',
            field=models.BooleanField(default=False, help_text='Mark the group as catalog.', verbose_name='Is Catalog'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='pcl_display_name',
            field=models.CharField(help_text='User-friendly display name', max_length=128, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='pcl_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ProductGroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='pcl_is_system',
            field=models.BooleanField(default=False, help_text='Is a system class type', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='pcl_name',
            field=models.CharField(help_text='Internal name, unique', max_length=128, unique=True, verbose_name='Internal Name'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='pgr_display_name',
            field=models.CharField(help_text='User-friendly display name', max_length=128, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='pgr_name',
            field=models.CharField(help_text='Internal name, unique', max_length=128, unique=True, verbose_name='Internal Name'),
        ),
    ]
