# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='tli_tilename',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Tilename'),
        ),
    ]
