# Generated by Django 2.1.5 on 2019-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0002_auto_20171220_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Status'),
        ),
    ]
