# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0002_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60, verbose_name='Internal Name')),
                ('tag_display_name',
                 models.CharField(blank=True, max_length=80, null=True, verbose_name='Display Name')),
                ('tag_install_date', models.DateField(blank=True, null=True, verbose_name='Install Date')),
                ('tag_release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('tag_status', models.BooleanField(default=False, verbose_name='Status')),
                ('tag_start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('tag_discovery_date', models.DateField(blank=True, null=True, verbose_name='Discovery Date')),
                ('tag_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Release',
                                                  verbose_name='Release')),
                ('tiles', models.ManyToManyField(related_name='tiles', to='coadd.Tile')),
            ],
        ),
    ]
