# Generated by Django 2.2.17 on 2021-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0004_release_rls_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='rls_is_public',
            field=models.BooleanField(default=False, help_text='Mark the release as public so that it is available to all users. uncheck it to make it available only to groups that have permission.', verbose_name='Is Public'),
        ),
    ]
