# Generated by Django 2.2.17 on 2021-05-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0005_release_rls_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgp_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_group_permission', to='coadd.Release', verbose_name='Release')),
                ('rgp_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Release', verbose_name='User Group')),
            ],
        ),
    ]
