# Generated by Django 2.2.17 on 2021-05-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0006_releasegrouppermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasegrouppermission',
            name='rgp_user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='User Group'),
        ),
    ]
