# Generated by Django 2.2.17 on 2021-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0007_auto_20210520_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='rls_tile_grid_enabled',
            field=models.BooleanField(default=False, help_text='Defines if aladin tile grid function will be active or not by default. util for releases that dont use the default DES area.', verbose_name='Tile Grid Enabled'),
        ),
    ]
