# Generated by Django 2.2.17 on 2023-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0007_auto_20210520_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='ncsa_original_path',
            field=models.TextField(blank=True, default=None, help_text='NCSA Original file path', null=True, verbose_name='NCSA Original Path'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='archive_path',
            field=models.TextField(blank=True, help_text='Base file path without root folder.', null=True, verbose_name='Archive Path'),
        ),
    ]
