# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0011_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='tli_dec',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_decll',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Decll'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_declr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Declr'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_decul',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Decul'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_decur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Decur'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_equinox',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='equinox'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_npix_dec',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='npix_dec'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_npix_ra',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='npix_ra'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_pixelsize',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='pixelsize'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_ra',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_rall',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RAll'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_ralr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RAlr'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_raul',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RAul'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_raur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RAur'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_udecll',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='udecll'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_udecur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='udecur'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_urall',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='urall'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tli_uraur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='uraur'),
        ),
    ]
