# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0012_auto_20160428_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='srv_target',
            field=models.CharField(blank=True,
                                   help_text='Initial position for this survey must be hours or degrees. Example: 02 21 36.957 -05 31 10.26 or 35.4832, -5.4800.',
                                   max_length=25, null=True, verbose_name='Target'),
        ),
    ]
