# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0013_release_rls_default'),
        ('coadd', '0015_auto_20160504_1722'),
    ]

    operations = [
    ]
