# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0017_auto_20160505_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='srv_filter',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
