# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('coadd', '0018_auto_20160520_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='srv_filter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='common.Filter', verbose_name='Filter'),
            preserve_default=False,
        ),
    ]
