# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0022_auto_20160812_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='image_src_ptif',
            field=models.URLField(blank=True, default=None, help_text='url complete for visiomatic ptif image, including the host and directory.use the release name and tilename to create the path. example: http://{host}/visiomatic?FIF=data/releases/{release_name}/images/visiomatic/{tilename}.ptif', null=True, verbose_name='Visiomatic PTIF'),
        ),
    ]
