# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0023_auto_20160826_1512'),
        ('coadd', '0023_auto_20160829_1846'),
    ]

    operations = [
    ]
