# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='archive_path',
            field=models.TextField(blank=True, help_text='Original file path', null=True, verbose_name='Archive Path'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Created Date'),
        ),
    ]
