# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0025_auto_20160915_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='tli_urall_180',
            field=models.FloatField(blank=True, default=0, help_text='urall in -180 a 180 degrees', null=True, verbose_name='urall 180'),
        ),
        migrations.AddField(
            model_name='tile',
            name='tli_uraur_180',
            field=models.FloatField(blank=True, default=0, help_text='uraur in -180 a 180 degrees', null=True, verbose_name='uraur 180'),
        ),
    ]
