# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0026_auto_20170403_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='srv_filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Filter', verbose_name='Filter'),
        ),
    ]
