# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='dsc_id',
        ),
        migrations.RemoveField(
            model_name='export',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='externalprocess',
            name='epr_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='ste_id',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='upl_id',
        ),
        migrations.AddField(
            model_name='discover',
            name='dsc_dummy',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='upload',
            name='upl_dummy',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
