# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(verbose_name='Owner')),
                ('event', models.CharField(max_length=100, verbose_name='Event')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Date')),
            ],
        ),
    ]
