# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-23 13:09
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='statistics',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
