# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pst_comment',
            field=models.TextField(max_length=2048, verbose_name='Comment'),
        ),
    ]
