# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-10 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pst_filter',
        ),
    ]
