# Generated by Django 2.1.5 on 2019-06-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dts_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coadd.Dataset', verbose_name='Dataset'),
        ),
    ]
