# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(help_text='Full URL to the path, including host name. Example: \thttp://{host}/data/releases/{release_name}/images/aladin/{band}', verbose_name='URL')),
            ],
        ),
    ]
