# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0076_auto_20170721_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(help_text='Full URL to the path, including host name. Example: \thttp://{host}/data/releases/{release_name}/images/aladin/{band}', verbose_name='URL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
        ),
    ]
