# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 19:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0005_auto_20160606_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_column_name', models.CharField(max_length=256, verbose_name='Column Name')),
                ('clm_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product',
                                                     verbose_name='Product')),
            ],
        ),
    ]
