# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coadd', '0017_auto_20160505_0104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftr_name', models.CharField(max_length=60, verbose_name='Internal Name')),
            ],
        ),
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flg_flagged', models.BooleanField(default=False, verbose_name='Flagged')),
                ('flg_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Dataset')),
                ('flg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
