# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 18:43
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coadd', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfc_ra', models.FloatField(blank=True, default=0, null=True, verbose_name='RA')),
                ('dfc_dec', models.FloatField(blank=True, default=0, null=True, verbose_name='Dec')),
                ('dfc_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Dataset', verbose_name='Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftr_name', models.CharField(max_length=60, verbose_name='Internal Name')),
            ],
        ),
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flg_flagged', models.BooleanField(default=False, verbose_name='Flagged')),
                ('flg_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Dataset')),
                ('owner', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='dfc_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Feature', verbose_name='Feature'),
        ),
        migrations.AddField(
            model_name='defect',
            name='dfc_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Filter', verbose_name='Filter'),
        ),
        migrations.AddField(
            model_name='defect',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
