# Generated by Django 2.1.5 on 2019-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagged',
            name='flg_flagged',
            field=models.BooleanField(blank=True, default=False, verbose_name='Flagged'),
        ),
    ]
