# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coadd', '0017_auto_20160505_0104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validation', '0002_auto_20160505_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfc_ra', models.FloatField(blank=True, default=0, null=True, verbose_name='RA')),
                ('dfc_dec', models.FloatField(blank=True, default=0, null=True, verbose_name='Dec')),
                ('dfc_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Dataset')),
                ('dfc_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Feature')),
                ('dfc_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Filter')),
                ('dfc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
