# Generated by Django 2.1.5 on 2019-06-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20190204_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagged',
            name='flg_flagged',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Flagged'),
        ),
    ]
