# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 19:47
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagged',
            name='flg_user',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
