# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 20:40
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_auto_20160512_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='dfc_user',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
