# Generated by Django 2.1.5 on 2019-06-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_auto_20190607_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagged',
            name='flg_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged', to='coadd.Dataset'),
        ),
    ]
