# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_auto_20160512_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='dfc_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='flagged',
            old_name='flg_dataset',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='flagged',
            old_name='flg_flagged',
            new_name='flagged',
        ),
        migrations.RenameField(
            model_name='flagged',
            old_name='flg_user',
            new_name='owner',
        ),
    ]
