# Generated by Django 2.1.5 on 2019-06-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspect',
            name='isp_dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspected', to='coadd.Dataset'),
        ),
    ]
