# Generated by Django 2.2.17 on 2021-04-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_auto_20190607_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
    ]
