# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 17:50
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('product_register', '0001_initial'),
        ('coadd', '0028_auto_20170807_1843'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_process_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_register.ExternalProcess', verbose_name='External Process'),
        ),
        migrations.AddField(
            model_name='product',
            name='releases',
            field=models.ManyToManyField(default=None, through='product.ProductRelease', to='coadd.Release', verbose_name='Releases'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(default=None, through='product.ProductTag', to='coadd.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='permission',
            name='prm_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='permission',
            name='prm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='permission',
            name='prm_workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Workgroup', verbose_name='Workgroup'),
        ),
        migrations.AddField(
            model_name='filterset',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='filterset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='fcd_property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductContent', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='filterset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Filterset', verbose_name='Filterset'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='cutout',
            name='cjb_cutout_job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.CutOutJob', verbose_name='Cutout Job'),
        ),
        migrations.AddField(
            model_name='cutout',
            name='ctt_filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Filter', verbose_name='Filter'),
        ),
        migrations.AddField(
            model_name='currentsetting',
            name='cst_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='currentsetting',
            name='cst_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSetting', verbose_name='Setting'),
        ),
        migrations.AddField(
            model_name='currentsetting',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='bookmarkproduct',
            name='owner',
            field=models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='bookmarkproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Table')),
                ('ctl_num_objects', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of objects')),
            ],
            bases=('product.table',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Table')),
                ('mpa_nside', models.PositiveSmallIntegerField(verbose_name='Nside')),
                ('mpa_ordering', models.CharField(max_length=8, verbose_name='Ordering')),
            ],
            bases=('product.table',),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Table')),
                ('msk_filter', models.CharField(max_length=1, verbose_name='Filter')),
            ],
            bases=('product.table',),
        ),
        migrations.AlterUniqueTogether(
            name='cutout',
            unique_together=set([('cjb_cutout_job', 'ctt_file_name')]),
        ),
        migrations.AlterIndexTogether(
            name='cutout',
            index_together=set([('cjb_cutout_job', 'ctt_object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkproduct',
            unique_together=set([('product', 'owner')]),
        ),
    ]
