# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_prd_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prd_process',
            new_name='prd_process_id',
        ),
    ]
