# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171212_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_is_public',
            field=models.BooleanField(default=False, help_text='Is Public default True', verbose_name='Is Public'),
        ),
    ]
