# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171212_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_is_public',
            field=models.BooleanField(default=False, help_text='Is Public default False', verbose_name='Is Public'),
        ),
    ]
