# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_classifier', '0007_auto_20160609_1418'),
        ('product', '0006_productcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContentAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pca_class_content',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='product_classifier.ProductClassContent', verbose_name='Class Content')),
                ('pca_product',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='product.Product', verbose_name='Product')),
                ('pca_product_content',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='product.ProductContent', verbose_name='Product Content')),
            ],
        ),
    ]
