# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20171213_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_is_permanent',
            field=models.BooleanField(default=False, help_text='Is Permanent default False, True so this product is not removed by the garbage collector', verbose_name='Is Permanent'),
        ),
    ]
