# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0008_auto_20160621_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ctl_num_columns',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of columns'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='ctl_num_objects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of objects'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='ctl_num_tiles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of tiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prd_flag_removed',
            field=models.BooleanField(default=False, help_text='True to mark a product as removed.',
                                      verbose_name='Is Removed'),
        ),
    ]
