# Generated by Django 2.1.5 on 2020-04-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190204_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ctl_num_objects',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Num of objects'),
        ),
        migrations.AlterField(
            model_name='table',
            name='tbl_rows',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Num of rows'),
        ),
    ]
