# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160621_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tbl_name',
            field=models.CharField(help_text='Tablename without schema', max_length=128, verbose_name='Tablename'),
        ),
    ]
