# Generated by Django 2.1.5 on 2020-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200420_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ctl_num_objects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of objects'),
        ),
    ]
