# Generated by Django 2.1.5 on 2020-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200903_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tbl_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Size in bytes'),
        ),
    ]
