# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20160726_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontentassociation',
            name='pca_class_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_classifier.ProductClassContent', verbose_name='Class Content'),
        ),
        migrations.AlterField(
            model_name='productcontentassociation',
            name='pca_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productcontentassociation',
            name='pca_product_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductContent', verbose_name='Product Content'),
        ),
    ]
