# Generated by Django 2.1.5 on 2020-11-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200903_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='ctt_download_finish_time',
        ),
        migrations.RemoveField(
            model_name='cutout',
            name='ctt_download_start_time',
        ),
    ]
