# Generated by Django 2.1.5 on 2020-11-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20201110_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='ctt_thumbname',
        ),
    ]
