# Generated by Django 2.1.5 on 2020-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_cutout_ctt_thumbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='ctt_img_format',
            field=models.TextField(blank=True, default=None, help_text='Image file format can be fits, stiff, or lupton.', max_length=10, null=True, verbose_name='Image Format'),
        ),
    ]
