# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 20:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coadd', '0025_auto_20160915_1437'),
        ('product', '0015_mask_msk_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Release')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coadd.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='releases',
            field=models.ManyToManyField(default=None, through='product.ProductRelease', to='coadd.Release',
                                         verbose_name='Releases'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(default=None, through='product.ProductTag', to='coadd.Tag',
                                         verbose_name='Tags'),
        ),
    ]
