# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0015_mask_msk_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='mpa_release',
        ),
        migrations.RemoveField(
            model_name='map',
            name='mpa_tag',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='msk_release',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='msk_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='prd_product_id',
            field=models.CharField(blank=True, help_text='Original Product Id', max_length=128, null=True,
                                   verbose_name='Product Id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prd_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prd_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Version'),
        ),
    ]
