# Generated by Django 2.2.17 on 2020-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_cutout_ctt_jobid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_Blacklist',
        ),
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_band',
        ),
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_image_formats',
        ),
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_job_type',
        ),
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_matched_file',
        ),
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_results_file',
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_fits_colors',
            field=models.CharField(blank=True, default='grizy', help_text="Color bands to output (string value containing characters from the set 'grizy').", max_length=10, null=True, verbose_name='Fits Colors'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_lupton_colors',
            field=models.CharField(blank=True, default='gri;rig;zgi', help_text='Sets of color band triplets, delineated by semi-colons, denoting by letter ordering the bands to use for Red, Green, Blue in the generated RGB images in Lupton format. Example: gri;zgi will produce two RGB images with Red/Green/Blue using bands G/R/I and Z/G/I, respectively.', max_length=20, null=True, verbose_name='Lupton Colors'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_make_fits',
            field=models.BooleanField(default=False, help_text='Generate cutout data files in FITS format', verbose_name='Make Fits'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_make_lupton',
            field=models.BooleanField(default=False, help_text='Generate cutout data files in RGB color using the Lupton method', verbose_name='Make Lupton'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_make_stiff',
            field=models.BooleanField(default=False, help_text='Generate cutout data files in RGB color using STIFF format', verbose_name='Make Stiff'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_stiff_colors',
            field=models.CharField(blank=True, default='gri;rig;zgi', help_text='Sets of color band triplets, delineated by semi-colons, denoting by letter ordering the bands to use for Red, Green, Blue in the generated RGB images in STIFF format. Example: gri;zgi will produce two RGB images with Red/Green/Blue using bands G/R/I and Z/G/I, respectively.', max_length=20, null=True, verbose_name='Stiff Colors'),
        ),
    ]
