# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20160926_2004'),
        ('product', '0016_auto_20160927_2014'),
    ]

    operations = [
    ]
