# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 20:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
        ('product', '0017_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='mpa_filter',
        ),
        migrations.AddField(
            model_name='product',
            name='prd_filter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='common.Filter', verbose_name='Filter'),
        ),
    ]
