# Generated by Django 2.2.17 on 2020-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20201111_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_file_size',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Total size of files generated in this job', null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_files',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Total of files generated in this job', null=True, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_make_stiff',
            field=models.BooleanField(default=True, help_text='Generate cutout data files in RGB color using STIFF format', verbose_name='Make Stiff'),
        ),
    ]
