# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20160928_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Filter', verbose_name='Filter'),
        ),
    ]
