# Generated by Django 2.2.17 on 2020-11-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20201111_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djb_jobid', models.CharField(blank=True, db_index=True, help_text='Descut job id that generated the image.', max_length=1024, null=True, verbose_name='DES Job ID')),
                ('djb_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='DES Job Status')),
                ('djb_cutout_job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.CutOutJob', verbose_name='Cutout Job')),
            ],
            options={
                'unique_together': {('djb_cutout_job', 'djb_jobid')},
            },
        ),
    ]
