# Generated by Django 2.2.17 on 2020-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_desjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='desjob',
            name='djb_message',
            field=models.TextField(blank=True, null=True, verbose_name='DES Job Message'),
        ),
    ]
