# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-07 20:08
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_table_tbl_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cst_display_name', models.CharField(max_length=128, verbose_name='Name')),
                ('cst_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('cst_is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('cst_is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('cst_owner', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('cst_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
        ),
    ]
