# Generated by Django 2.2.17 on 2020-11-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_desjob_djb_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='cjb_des_job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Desjob', verbose_name='Des Job'),
        ),
    ]
