# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsettings',
            old_name='cst_owner',
            new_name='owner',
        ),
    ]
