# Generated by Django 2.2.17 on 2020-11-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_cutout_cjb_des_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='desjob',
            name='djb_finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='desjob',
            name='djb_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start'),
        ),
    ]
