# Generated by Django 2.2.17 on 2020-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20201117_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_job_id',
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_error',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
    ]
