# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_currentsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentSettings',
            new_name='CurrentSetting',
        ),
    ]
