# Generated by Django 2.2.17 on 2021-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20201119_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutout',
            name='ctt_object_id',
            field=models.CharField(blank=True, help_text='The association is used to know which column will be considered as id.', max_length=255, null=True, verbose_name='Object ID'),
        ),
    ]
