# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20161014_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSettings',
            new_name='ProductSetting',
        ),
    ]
