# Generated by Django 2.2.17 on 2021-05-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210510_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_traceback',
            field=models.TextField(blank=True, null=True, verbose_name='Error Traceback'),
        ),
    ]
