# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20161014_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontentassociation',
            name='pca_setting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSetting', verbose_name='Setting'),
        ),
    ]
