# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productcontentassociation_pca_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontentassociation',
            name='pca_setting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSetting', verbose_name='Setting'),
        ),
    ]
