# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20161017_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsetting',
            name='cst_is_public',
        ),
        migrations.AddField(
            model_name='productsetting',
            name='cst_is_editable',
            field=models.BooleanField(default=False, verbose_name='Is Editable'),
        ),
    ]
