# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20161019_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsetting',
            name='cst_is_default',
        ),
        migrations.AddField(
            model_name='productsetting',
            name='cst_is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
    ]
