# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20161019_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContentSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs_is_visible', models.BooleanField(default=False, verbose_name='Is Visible')),
                ('pcs_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('pcs_content', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductContent', verbose_name='Content')),
                ('pcs_setting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSetting', verbose_name='Setting')),
            ],
        ),
    ]
