# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 13:16
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0030_productcontentsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctt_url', models.CharField(max_length=20, verbose_name='url')),
                ('ctt_object_id', models.CharField(max_length=5, verbose_name='Object ID')),
                ('ctt_ra', models.CharField(max_length=5, verbose_name='ra')),
                ('ctt_dec', models.CharField(max_length=5, verbose_name='Dec')),
                ('ctt_tipo', models.CharField(max_length=5, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='CutOutJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cjb_display_name', models.CharField(max_length=20, verbose_name='Name')),
                ('cjb_xsize', models.CharField(max_length=5, verbose_name='Xsize')),
                ('cjb_ysize', models.CharField(max_length=5, verbose_name='ysize')),
                ('cjb_job_type', models.CharField(max_length=10, verbose_name='JobType')),
                ('cjb_band', models.CharField(max_length=10, null=True, verbose_name='band')),
                ('cjb_Blacklist', models.CharField(max_length=10, null=True, verbose_name='Blacklist')),
                ('cjb_status', models.CharField(choices=[('st', 'start'), ('bs', 'beforeSubmit'), ('rn', 'running'), ('ok', 'done')], default='st', max_length=2, verbose_name='Status')),
                ('cjb_job_id', models.CharField(max_length=1024, verbose_name='Job ID')),
                ('cjb_product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
                ('owner', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.AddField(
            model_name='cutout',
            name='cjb_cutout_job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.CutOutJob', verbose_name='CutOutJob'),
        ),
        migrations.AddField(
            model_name='cutout',
            name='ctt_filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Filter', verbose_name='Filter'),
        ),
    ]
