# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20161111_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_user_display_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='User Display Name'),
        ),
    ]
