# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_product_prd_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tbl_num_columns',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of columns'),
        ),
        migrations.AddField(
            model_name='table',
            name='tbl_rows',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num of rows'),
        ),
    ]
