# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20161215_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tbl_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Size in bytes'),
        ),
    ]
