# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_product_prd_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_process_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_register.ExternalProcess', verbose_name='External Process'),
        ),
    ]
