# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_prd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
