# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20170127_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_is_public',
            field=models.BooleanField(default=True, help_text='Is Public default True', verbose_name='Is Public'),
        ),
    ]
