# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_prd_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of registration.', null=True, verbose_name='Date'),
        ),
    ]
