# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-14 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prd_flag_removed',
        ),
    ]
