# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_remove_product_prd_flag_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='ctt_tipo',
        ),
        migrations.RemoveField(
            model_name='cutout',
            name='ctt_url',
        ),
        migrations.AddField(
            model_name='cutout',
            name='ctt_file_path',
            field=models.CharField(default='---', max_length=20, verbose_name='File Path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutout',
            name='ctt_file_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='File Extension'),
        ),
        migrations.AlterField(
            model_name='cutout',
            name='ctt_dec',
            field=models.CharField(blank=True, help_text='Dec in degrees, the association will be used to identify the column', max_length=5, null=True, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='cutout',
            name='ctt_object_id',
            field=models.CharField(blank=True, help_text='The association is used to know which column will be considered as id.', max_length=5, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='cutout',
            name='ctt_ra',
            field=models.CharField(blank=True, help_text='RA in degrees, the association will be used to identify the column', max_length=5, null=True, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_Blacklist',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Blacklist'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_band',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='band'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_status',
            field=models.CharField(choices=[('st', 'Start'), ('bs', 'Submit'), ('rn', 'Running'), ('ok', 'Done'), ('er', 'Error')], default='st', max_length=2, verbose_name='Status'),
        ),
    ]
