# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20170216_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutout',
            name='ctt_file_type',
            field=models.CharField(default='---', max_length=5, verbose_name='File Extension'),
            preserve_default=False,
        ),
    ]
