# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20170221_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='ctt_download_finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Download finish'),
        ),
        migrations.AddField(
            model_name='cutout',
            name='ctt_download_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Download Start'),
        ),
        migrations.AddField(
            model_name='cutout',
            name='ctt_file_size',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='File Size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='cutout',
            name='cjb_cutout_job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.CutOutJob', verbose_name='Cutout Job'),
        ),
    ]
