# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-21 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20170221_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cutout',
            unique_together=set([('cjb_cutout_job', 'ctt_file_name')]),
        ),
    ]
