# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-22 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20170221_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutout',
            old_name='ctt_dec',
            new_name='ctt_object_dec',
        ),
        migrations.RenameField(
            model_name='cutout',
            old_name='ctt_ra',
            new_name='ctt_object_ra',
        ),
    ]
