# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20170222_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='ctt_thumbname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Thumbname'),
        ),
    ]
