# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-26 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_cutout_ctt_thumbname'),
        ('product', '0045_productcontent_pcn_ucd'),
    ]

    operations = [
    ]
