# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20170503_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prl_cross_identification', models.ForeignKey(default=None, help_text='Foreign key between the product and the related product', on_delete=django.db.models.deletion.CASCADE, to='product.ProductContent', verbose_name='Cross Identification')),
                ('prl_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Product', verbose_name='Product')),
                ('prl_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='product.Product', verbose_name='Related Product')),
            ],
        ),
    ]
