# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 17:23
from __future__ import unicode_literals

import current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0055_auto_20170504_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcd_operation', models.CharField(max_length=10, verbose_name='Operator')),
                ('fcd_value', models.CharField(max_length=10, verbose_name='Value')),
                ('fcd_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductContent', verbose_name='Property')),
            ],
        ),
        migrations.CreateModel(
            name='Filterset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst_name', models.CharField(help_text='Filterset Display Name', max_length=60, verbose_name='Filterset')),
                ('owner', models.ForeignKey(default=current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='filterset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Filterset', verbose_name='Filterset'),
        ),
    ]
