# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-18 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_auto_20170512_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercondition',
            name='fcd_property_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the property like this in the database', max_length=60, null=True, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='filtercondition',
            name='fcd_property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductContent', verbose_name='Property'),
        ),
    ]
