# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_auto_20170519_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_band',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_job_type',
            field=models.CharField(choices=[('coadd', 'Coadd Images'), ('single', 'Single Epoch')], max_length=10, verbose_name='Job Type'),
        ),
    ]
