# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_auto_20170519_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_Blacklist',
            field=models.BooleanField(default=False, help_text='Exclude blacklisted ccds', verbose_name='Blacklist'),
        ),
    ]
