# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_bookmarkproduct_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkproduct',
            name='is_owner',
        ),
    ]
