# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_remove_bookmarkproduct_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_status',
            field=models.CharField(choices=[('st', 'Start'), ('bs', 'Submit Job'), ('rn', 'Running'), ('ok', 'Done'), ('er', 'Error'), ('je', 'Job Error'), ('dl', 'Delete')], default='st', max_length=2, verbose_name='Status'),
        ),
    ]
