# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20170608_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_label_position',
            field=models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside')], help_text="This field determines the position of the labels, 'inside' for labels on the image and 'outside' for labels outside the image.", max_length=10, null=True, verbose_name='Label Position'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_label_properties',
            field=models.CharField(blank=True, help_text='A list with the ids of the properties that will be used as a label. (Id = ProductContent.pk)', max_length=1024, null=True, verbose_name='Label Properties'),
        ),
    ]
