# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_cutoutjob_cjb_label_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_label_colors',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Label Colors'),
        ),
    ]
