# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-12 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20170609_2105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarkproduct',
            unique_together=set([('product', 'owner')]),
        ),
    ]
