# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_auto_20170612_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_label_font_size',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Font size in px.', null=True, verbose_name='Label Font Size'),
        ),
    ]
