# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_auto_20170612_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_matched_file',
            field=models.CharField(blank=True, default=None, help_text='File containing the relations between ra, dec with the image', max_length=4096, null=True, verbose_name='Matched File'),
        ),
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_results_file',
            field=models.CharField(blank=True, default=None, help_text='File that contains the links returned by the DesCutouts service', max_length=4096, null=True, verbose_name='Result File'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_status',
            field=models.CharField(choices=[('st', 'Start'), ('bs', 'Submit Job'), ('rn', 'Running'), ('bd', 'Before Download'), ('dw', 'Downloading'), ('ok', 'Done'), ('er', 'Error'), ('je', 'Job Error'), ('dl', 'Delete')], default='st', max_length=2, verbose_name='Status'),
        ),
    ]
