# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20170713_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_label_position',
            field=models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside')], default='outside', help_text="This field determines the position of the labels, 'inside' for labels on the image and 'outside' for labels outside the image.", max_length=10, null=True, verbose_name='Label Position'),
        ),
        migrations.AlterField(
            model_name='cutoutjob',
            name='cjb_status',
            field=models.CharField(choices=[('st', 'Start'), ('bs', 'Submit Job'), ('rn', 'Running'), ('bd', 'Before Download'), ('dw', 'Downloading'), ('ok', 'Done'), ('er', 'Error'), ('je', 'Job Error'), ('dl', 'Delete')], default='st', max_length=25, verbose_name='Status'),
        ),
    ]
