# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-18 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_auto_20170714_1823'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='cutout',
            index_together=set([('cjb_cutout_job', 'ctt_object_id')]),
        ),
    ]
