# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_auto_20170721_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_cutouts_path',
            field=models.CharField(blank=True, default=None, help_text='Path of the directory where the cutouts of this job are.', max_length=4096, null=True, verbose_name='Cutout Paths'),
        ),
    ]
