# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-06 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_cutoutjob_cjb_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutoutjob',
            name='cjb_attempts',
        ),
    ]
