# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_remove_cutoutjob_cjb_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
