# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_cutoutjob_cjb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutjob',
            name='cjb_image_formats',
            field=models.CharField(blank=True, help_text="list of image extensions that will be downloaded from the descut. example 'png,fits'", max_length=10, null=True, verbose_name='Image Formats'),
        ),
    ]
