# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.IntegerField(verbose_name='Catalog')),
                ('owner', models.IntegerField(verbose_name='Owner')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object Id')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Date')),
                ('comments', models.TextField(verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.IntegerField(verbose_name='Catalog')),
                ('owner', models.IntegerField(verbose_name='Owner')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object Id')),
                ('rating', models.IntegerField(verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.IntegerField(verbose_name='Catalog')),
                ('owner', models.IntegerField(verbose_name='Owner')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object Id')),
                ('reject', models.BooleanField(default=False, verbose_name='Reject')),
            ],
        ),
    ]
