# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-03 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Date'),
        ),
    ]
