# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170503_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.CharField(max_length=255, verbose_name='Object Id'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='object_id',
            field=models.CharField(max_length=255, verbose_name='Object Id'),
        ),
    ]
