# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170602_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.CharField(max_length=255, verbose_name='Object Id'),
        ),
    ]
